### ISSUE TITLE
Performance profiling and benchmarking

### ISSUE THREAD

**Issue by t-imamichi** [Qiskit/qiskit-optimization#99]
### What is the expected enhancement?

We need performance profiling of our codes to identify performance issues. We would like to setup an [airspeed velocity](https://qiskit.github.io/qiskit/) like terra.
For example, we think of Maxcut as an example of a benchmark. We measure the computation time with different numbers of nodes to check the scaling.

TODO:
- [ ] Pickup problems and algorithms for benchmarks
- [ ] Implement benchmarks (test/benchmarks?)
- [ ] Setup airspeed velocity

References:
- Terra's asv https://qiskit.github.io/qiskit/
- https://github.com/Qiskit/qiskit/tree/master/test/benchmarks
- https://github.com/Qiskit/qiskit-aer/tree/master/test/benchmark

**Comment by woodsp-ibm** [comment]
I think there are 2 aspects here, so `Performance profiling and benchmarking.` The code can be investigated to identify bottlenecks etc and improve performance via profiling. Then, to assure performance does not deteriorate over changes, and even see improvements that may come from elsewhere, a benchmark suite can be developed. Maybe here this Issue is more about setting up the benchmark suite.

**Comment by t-imamichi** [comment]
Because we have https://github.com/Qiskit/qiskit-app-benchmarks, I close this issue.
